### ISSUE TITLE
Error: "undefined is not a function", fs.createReadStream

### ISSUE THREAD

**Issue by thomasnordlund** [mapmeld/node-rhyme#1]
When I try to use your module, I get an "undefined is not a function" error at line 112: 

```
var s = fs.createReadStream(dictFileDirect || dictFile);
```

The File System module is installed by default, no? Any idea what might be going on?

**Comment by mapmeld** [comment]
I don't know... did you find out what was wrong? Even if it's simple, it could be added to the README

**Comment by HungryDinosaur** [comment]
I get this error when I use the module on the client. Any thoughts?

**Comment by mapmeld** [comment]
@HungryDinosaur this module requires the CMU phonetic dictionary dataset (which is 3.7 mb text uncompressed). You will need to use gzip / compression middleware for your server-side framework / or have some patience.

If you're continuing on, I would recommend using browserify or another Node->client-side JS tool to support the fs module, or using an AJAX request to fetch this dataset instead of using fs.

**Comment by HungryDinosaur** [comment]
@mapmeld hey Nick, thanks for the quick response!

This is more or less what I thought, serving the dictionary sounds like a pain. I think for now I'll keep the rhyming code on the server and just sync the results to the client. For reference the app is a Meteor project.
